import { ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    // absolute: "",
    default: "NextJS Tutorial - Codevolution",
    template: "%s | Codevolution",
  },
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
};

function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="p-[1rem] bg-blue-400">
          <p>Header</p>
        </header>

        {children}

        <footer className="p-[1rem] bg-slate-400">footer</footer>
      </body>
    </html>
  );
}

export default RootLayout;
