import { ReactNode } from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Auth section",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
};

function RootLayout({ children }: Props) {
  return (
    <div>
      <h2>Inner layout</h2>
      {children}
    </div>
  );
}

export default RootLayout;
