import { ReactNode } from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Complex Dashboard",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
  notifications: ReactNode;
  revenue: ReactNode;
  users: ReactNode;
  login: ReactNode;
};

function ComplexLayout({
  children,
  notifications,
  revenue,
  users,
  login,
}: Props) {
  const isLoggedIn = false;
  return isLoggedIn ? (
    <div>
      <h1>{children}</h1>
      <div style={{ display: "flex" }}>
        <div style={{ display: "flex", flexDirection: "column" }}>
          <div>{users}</div>
          <div>{revenue}</div>
        </div>
        <div style={{ display: "flex", flex: 1 }}>{notifications}</div>
      </div>
    </div>
  ) : (
    { login }
  );
}

export default ComplexLayout;
