import { ReactNode } from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Complex Dashboard",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
  notifications: ReactNode;
  revenue: ReactNode;
  users: ReactNode;
};

function ComplexLayout({ children, notifications, revenue, users }: Props) {
  return (
    <div>
      <h1>{children}</h1>
      <div style={{ display: "flex" }}>
        <div style={{ display: "flex", flexDirection: "column" }}>
          <div>{users}</div>
          <div>{revenue}</div>
        </div>
        <div style={{ display: "flex", flex: 1 }}>{notifications}</div>
      </div>
    </div>
  );
}

export default ComplexLayout;
